#14 [auction] 입찰하기 기능 구현
jshstar/ticket-auction-backend pull request #90
Opened 2024-01-09 09:03 UTC by Kminss

- 5% 이상 상회입찰가면 DB저장 후 Redis에  입찰가 갱신 => 추후 DB 저장도 비동기로 처리하면 더 좋을 것 같음

 - ToDo: 일정 여윺되면 알림기능도 연동

## 개요 📝

Resolves: #14 

## PR 유형 ✅
어떤 변경 사항이 있나요?

- [X] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist ✅
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [X] 커밋 메시지 컨벤션에 맞게 작성했습니다.
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

<br>

## 작업사항 🛠️
<br>

## 변경로직 ⚠️ 
<br>

### 변경전
<br>

### 변경후
<br>

## 기타

2024-01-09 09:28 UTC, kimhyeyun approved these changes
좋슴돠~ 고생하셨습니다~~

2024-01-09 11:15 UTC, OuOHoon requested changes
고생하셨습니다~

2024-01-09 11:15 UTC, OuOHoon commented on src/main/java/com/sparta/ticketauction/domain/auction/service/BidServiceImpl.java
> +		if (increaseBidPrice > bidPrice) {
입찰시 현재 유저가 포인트를 입찰 가능한만큼 보유하고 있는지 확인하는 과정이 필요하다고 생각하는데 어떻게 생각하시나요~? 아니면 다른 서비스에서 처리하실 예정일까요~?

2024-01-09 17:28 UTC, Kminss commented on src/main/java/com/sparta/ticketauction/domain/auction/service/BidServiceImpl.java
> +		if (increaseBidPrice > bidPrice) {
수정했습니다. 
우선 직접 userRepo에서 point 
다만 해당서비스에서 바로 하는것보다 
Point 관련된 서비스레이어에서 `포인트 결제` 라는 서비스를 구현하고 해당 서비스 클래스를 의존하는 식으로
변경해야 할 것 같습니다.

2024-01-10 03:49 UTC, OuOHoon approved these changes

2024-01-10 06:02 UTC, kimhyeyun approved these changes
고생하셨습니당~

2024-01-10 10:26 UTC, merged